### ISSUE TITLE
question: About the number of PCA components

### ISSUE THREAD

**Issue by mohaEs** [justusschock/shapenet#18]
In your experimental environment, you have 68 landmarks for each face and you set the PCA components to 25 in the config file. Based on your experience, what would be a suitable choice of PCA components if we have just 23 landmarks in each image?
Thanks in advance.

**Comment by justusschock** [comment]
The following answer is based on the assumption, that you are also dealing with faces and not some other image modality, because the answer does not depend on the number of landmarks but on the variance of the positions.

For example if you have a dataset consisting only of frontal faces you need much less parameters than you'd need for rotated faces, despite having the same number of parameters. 

An upper bound is the number of landmark coordinates, you're having. So for 23 landmarks in a 2d setup, you have a maximum of 23*2=46 components. I guess I'd start with 15 components or something like that and evaluate the impact of variations of this number.
