### ISSUE TITLE
wrong angle

### ISSUE THREAD

**Issue by divastar** [justusschock/shapenet#24]
Hi I got some predictions which have wrong rotation angle.
Is there suggestions how I can work on that?
![foots_3_5](https://user-images.githubusercontent.com/50579056/59329945-c5cf8380-8cf8-11e9-8d41-8dd684c1c1d4.png)
thank you

**Comment by justusschock** [comment]
Well what I see from your image it's really hard to give a accurate keypoint prediction with a low resolution as yours. Nevertheless: 
* Are you sure, you plotted it correctly (not switched x and y etc.)? 
* Do you have several images with a rotation like this inside your trainset? 
* What are your training parameters?

**Comment by dinghou123** [comment]
in the predictor.py,How to set the key_mapping?

 mapped_data = {
            k: data[v] for k, v in self.key_mapping.items()}

I don't find the arguments.What is the key_mapping should Pass?

**Comment by justusschock** [comment]
You need to use an older version of `delira`. 0.3.2 should work I think. I haven't tested this with the current stable release, but if you want to do so, the key_mapping would be `{"input_images": "data"}` since the network's forward accepts the key `input_images` and the image is stored under the key `data`
